name: opera
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openssl=1.1.1t
  - pillow=9.4.0
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.9.16
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.29.0
  - setuptools=66.0.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=0.12.1
  - typing_extensions=4.5.0
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.19.0
      - aiofiles==23.1.0
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - altair==4.2.2
      - antlr4-python3-runtime==4.9.3
      - anyio==3.6.2
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.2.3
      - asttokens==2.2.1
      - async-lru==2.0.2
      - async-timeout==4.0.2
      - attrs==23.1.0
      - babel==2.12.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bertviz==1.4.0
      - bitsandbytes==0.39.0
      - bleach==6.0.0
      - blinker==1.6.2
      - blis==0.7.9
      - boto3==1.28.63
      - botocore==1.31.63
      - braceexpand==0.1.7
      - cachetools==5.3.0
      - catalogue==2.0.8
      - cfgv==3.3.1
      - click==8.1.3
      - cmake==3.26.3
      - comm==0.1.3
      - confection==0.0.4
      - contexttimer==0.3.3
      - contourpy==1.0.7
      - curated-tokenizers==0.0.8
      - curated-transformers==0.1.1
      - cycler==0.11.0
      - cymem==2.0.7
      - debugpy==1.6.7
      - decorator==5.1.1
      - decord==0.6.0
      - defusedxml==0.7.1
      - distlib==0.3.6
      - distro==1.8.0
      - einops==0.6.1
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - executing==1.2.0
      - fairscale==0.4.4
      - fastapi==0.95.2
      - fastjsonschema==2.16.3
      - ffmpy==0.3.0
      - filelock==3.12.0
      - fonttools==4.39.4
      - fqdn==1.5.1
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - ftfy==6.1.1
      - gdown==4.7.1
      - gitdb==4.0.10
      - gitpython==3.1.31
      - gradio==3.31.0
      - gradio-client==0.2.5
      - h11==0.14.0
      - httpcore==0.17.1
      - httpx==0.24.1
      - huggingface-hub==0.14.1
      - identify==2.5.24
      - imageio==2.28.1
      - importlib-metadata==6.6.0
      - importlib-resources==5.12.0
      - iopath==0.1.10
      - ipykernel==6.23.1
      - ipython==8.13.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.0.6
      - isoduration==20.11.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.2.0
      - json5==0.9.14
      - jsonpointer==2.3
      - jsonschema==4.17.3
      - jupyter==1.0.0
      - jupyter-client==8.2.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.0
      - jupyter-events==0.6.3
      - jupyter-lsp==2.1.0
      - jupyter-server==2.5.0
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.7
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.22.1
      - jupyterlab-widgets==3.0.7
      - kaggle==1.5.13
      - kiwisolver==1.4.4
      - langcodes==3.3.0
      - lazy-loader==0.2
      - linkify-it-py==2.0.2
      - lit==16.0.5
      - markdown-it-py==2.2.0
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mistune==2.0.5
      - mpmath==1.3.0
      - multidict==6.0.4
      - murmurhash==1.0.9
      - nbclassic==1.0.0
      - nbclient==0.7.4
      - nbconvert==7.4.0
      - nbformat==5.8.0
      - nest-asyncio==1.5.6
      - networkx==3.1
      - nltk==3.8.1
      - nodeenv==1.8.0
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.3.0
      - openai==0.28.1
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - openpyxl==3.1.2
      - orjson==3.8.12
      - packaging==23.1
      - pandas==2.0.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathy==0.10.1
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - platformdirs==3.5.1
      - plotly==5.14.1
      - portalocker==2.7.0
      - pre-commit==3.3.2
      - preshed==3.0.8
      - prometheus-client==0.16.0
      - prompt-toolkit==3.0.38
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.6
      - pydantic==1.10.7
      - pydeck==0.8.1b0
      - pydub==0.25.1
      - pygments==2.15.1
      - pympler==1.0.1
      - pyparsing==3.0.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - python-magic==0.4.27
      - python-multipart==0.0.6
      - python-slugify==8.0.1
      - pytz==2023.3
      - pywavelets==1.4.1
      - pyyaml==6.0
      - pyzmq==25.0.2
      - qtconsole==5.4.3
      - qtpy==2.3.1
      - regex==2023.5.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.3.5
      - s3transfer==0.7.0
      - safetensors==0.3.1
      - scikit-image==0.20.0
      - scikit-learn==1.2.2
      - scipy==1.9.1
      - seaborn==0.13.0
      - semantic-version==2.10.0
      - send2trash==1.8.2
      - sentencepiece==0.1.99
      - six==1.16.0
      - sklearn==0.0.post5
      - smart-open==6.3.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - spacy==3.7.0.dev0
      - spacy-curated-transformers==0.2.0
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - srsly==2.4.6
      - stack-data==0.6.2
      - starlette==0.27.0
      - streamlit==1.22.0
      - sympy==1.12
      - tenacity==8.2.2
      - terminado==0.17.1
      - text-unidecode==1.3
      - thinc==8.1.10
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - timm==0.4.12
      - tinycss2==1.2.1
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.0.1
      - toolz==0.12.0
      - torch==2.0.1
      - torchvision==0.15.2
      - tornado==6.3.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - triton==2.0.0
      - typer==0.7.0
      - tzdata==2023.3
      - tzlocal==5.0.1
      - uc-micro-py==1.0.2
      - uri-template==1.2.0
      - uvicorn==0.22.0
      - validators==0.20.0
      - virtualenv==20.23.0
      - wasabi==1.1.1
      - watchdog==3.0.0
      - wcwidth==0.2.6
      - webcolors==1.13
      - webdataset==0.2.48
      - webencodings==0.5.1
      - websocket-client==1.5.1
      - websockets==11.0.3
      - widgetsnbextension==4.0.7
      - yarl==1.9.2
      - zipp==3.15.0
